// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1DLyLa0AiBNPLSIQUtMO631mJG1AeTrA',
    appId: '1:696262124909:web:6735dfc158ce9e3fcda664',
    messagingSenderId: '696262124909',
    projectId: 'ideal-playground',
    authDomain: 'ideal-playground.firebaseapp.com',
    storageBucket: 'ideal-playground.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2n7nDrf12gytS3fgMuRpX8ZUcRhYzvpU',
    appId: '1:696262124909:android:e87cf86c5b63539ecda664',
    messagingSenderId: '696262124909',
    projectId: 'ideal-playground',
    storageBucket: 'ideal-playground.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAln7RGq9nrwWOIZAkk59jq3oVwNPulOT0',
    appId: '1:696262124909:ios:8524f0a0a355e317cda664',
    messagingSenderId: '696262124909',
    projectId: 'ideal-playground',
    storageBucket: 'ideal-playground.appspot.com',
    iosClientId: '696262124909-8128hegjoco6oas9nl8p3kou77hsgpns.apps.googleusercontent.com',
    iosBundleId: 'com.example.idealPlayground',
  );
}
